name: lprint
version: 1.0b1
summary: Label Printer Utility
description: |
   LPrint implements printing for a variety of common label and receipt printers
   connected via network or USB.  Features include:

   - A single executable handles spooling, status, and server functionality.
   - Multiple printer support.
   - Each printer implements an IPP Everywhere™ print service and is compatible
     with the driverless printing support in iOS, macOS, and Linux clients.
   - Each printer can support options such as label modes, tear-off offsets,
     media tracking, media top offset, print darkness, resolution, roll
     selection, and speed.
   - Each printer can print "raw", Apple/PWG Raster, and/or PNG files.

   For more information, see the file "DOCUMENTATION.md", the man pages in the
   "man" directory, and/or the LPrint project page at
   "https://www.msweet.org/lprint".

grade: stable
confinement: strict
icon: lprint.png

apps:
    lprint:
        command: bin/lprint
        plugs: [avahi-observe, home, network, network-bind, raw-usb]

parts:
    libcups:
        plugin: autotools
        configflags: [--with-components=libcupslite]
        source: https://github.com/apple/cups/releases/download/v2.3.1/cups-2.3.1-source.tar.gz
        build-packages: [libavahi-client-dev, libgnutls28-dev, zlib1g-dev]
        prime:
            - -bin/*
            - -include/cups/*
            - -lib/*
        stage:
            - -lib/*
    libpng:
        plugin: autotools
        source: https://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz
        build-packages: [zlib1g-dev]
        prime:
            - -include/*
            - -lib/*
            - -lib/pkg-config/*
        stage:
            - -lib/*
    libusb:
        plugin: autotools
        source: https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.tar.bz2
        build-packages: [libudev-dev]
        prime:
            - -include/*
            - -lib/*
            - -lib/pkg-config/*
        stage:
            - -lib/*
    main:
        after: [libcups, libpng, libusb]
        plugin: autotools
        configflags: [--enable-libpng,--enable-libusb,--with-dnssd=avahi,--with-ldflags="-L$SNAPCRAFT_PART_INSTALL/../../libcups/install/lib"]
        source: .
        build-packages: [libavahi-client-dev, libgnutls28-dev, zlib1g-dev]
        stage-packages: [libavahi-client3]

