name: lprint
version: 1.0b1
summary: Label Printer Utility
description: |
   LPrint implements printing for a variety of common label and receipt printers
   connected via network or USB.  Features include:

   - A single executable handles spooling, status, and server functionality.
   - Multiple printer support.
   - Each printer implements an IPP Everywhere™ print service and is compatible
     with the driverless printing support in iOS, macOS, and Linux clients.
   - Each printer can support options such as label modes, tear-off offsets,
     media tracking, media top offset, print darkness, resolution, roll
     selection, and speed.
   - Each printer can print "raw", Apple/PWG Raster, and/or PNG files.

   For more information, see the file "DOCUMENTATION.md", the man pages in the
   "man" directory, and/or the LPrint Home Page at
   "https://www.msweet.org/lprint".

grade: stable
confinement: strict
icon: lprint.png

apps:
    lprint:
        command: bin/lprint
        plugs: [avahi-observe, home, network, network-bind]

parts:
    main:
        plugin: autotools
        source: .
        build-packages: [libavahi-client-dev, libcups2-dev, libcupsimage2-dev, libgnutls28-dev, libpng-dev, zlib1g-dev]
        stage-packages: [libavahi-client3]
