name: lprint
base: core20
version: "1.1"
summary: A Label Printer Application
description: |
   LPrint implements printing for a variety of common label and receipt printers
   connected via network or USB.  Features include:

   - A single executable handles spooling, status, and server functionality.
   - Multiple printer support.
   - Each printer implements an IPP Everywhere™ print service and is compatible
     with the driverless printing support in iOS, macOS, and Linux clients.
   - Each printer can support options such as label modes, tear-off offsets,
     media tracking, media top offset, print darkness, resolution, roll
     selection, and speed.
   - Each printer can print "raw", Apple/PWG Raster, and/or PNG files.

   For more information, see the file "DOCUMENTATION.md", the man pages in the
   "man" directory, and/or the LPrint project page at
   "https://www.msweet.org/lprint".

grade: stable
confinement: strict
icon: static-resources/lprint.png

apps:
    lprint:
        command: bin/lprint
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

parts:
    pappl:
        plugin: autotools
        configflags: [--enable-libjpeg,--enable-libpng,--enable-libusb,--with-dnssd=avahi]
        source: https://github.com/michaelrsweet/pappl/releases/download/v1.1.0/pappl-1.1.0.tar.gz
        build-packages: [libavahi-client-dev, libcups2-dev, libcupsimage2-dev, libgnutls28-dev, libjpeg8-dev, libpam-dev, libpng-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libcups2, libcupsimage2, libjpeg8, libpng16-16, libusb-1.0-0]

    lprint:
        plugin: autotools
        configflags: [--enable-libpng,--enable-libusb,--with-dnssd=avahi]
        source: .
        after: [pappl]
        build-packages: [libavahi-client-dev, libcups2-dev, libcupsimage2-dev, libgnutls28-dev, libpng-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libcups2, libcupsimage2, libpng16-16, libusb-1.0-0]
